<?xml version="1.0" encoding="utf-8"?><Database Name="NewsApplicationDB" Class="NewsApplicationDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SAEED\MSSQLSERVER01;Initial Catalog=NewsApplicationDB;Integrated Security=True" SettingsObjectName="FileWorksObject.My.MySettings" SettingsPropertyName="NewsApplicationDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_BUSINESSOBJECT" Member="T_BUSINESSOBJECTs">
    <Type Name="T_BUSINESSOBJECT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="C_CREATIONDATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="C_NAME" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="C_CLASSID" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="C_LASTMODIFIER" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="T_BUSINESSOBJECT_T_FILE" Member="T_FILE" ThisKey="ID" OtherKey="ID" Type="T_FILE" Cardinality="One" />
      <Association Name="T_BUSINESSOBJECT_T_USER" Member="T_USER" ThisKey="ID" OtherKey="ID" Type="T_USER" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.T_FILE" Member="T_FILEs">
    <Type Name="T_FILE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="C_BODY" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="C_TAGGED" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="C_Description" Type="System.Data.Linq.Binary" DbType="VarBinary(255)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="T_FILE_T_NEW" Member="T_NEW" ThisKey="ID" OtherKey="ID" Type="T_NEW" Cardinality="One" />
      <Association Name="T_FILE_T_PHOTO" Member="T_PHOTO" ThisKey="ID" OtherKey="ID" Type="T_PHOTO" Cardinality="One" />
      <Association Name="T_BUSINESSOBJECT_T_FILE" Member="T_BUSINESSOBJECT" ThisKey="ID" OtherKey="ID" Type="T_BUSINESSOBJECT" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_NEWS" Member="T_NEWs">
    <Type Name="T_NEW">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="C_CATEGORY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="T_FILE_T_NEW" Member="T_FILE" ThisKey="ID" OtherKey="ID" Type="T_FILE" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_PHOTO" Member="T_PHOTOs">
    <Type Name="T_PHOTO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="C_LOCATION" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="T_FILE_T_PHOTO" Member="T_FILE" ThisKey="ID" OtherKey="ID" Type="T_FILE" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_USER" Member="T_USERs">
    <Type Name="T_USER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="C_FULLNAME" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="C_PASSWORD" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="C_PRIVILEGELEVEL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="T_BUSINESSOBJECT_T_USER" Member="T_BUSINESSOBJECT" ThisKey="ID" OtherKey="ID" Type="T_BUSINESSOBJECT" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>